/// Generated constants related to the ChromeDriver version and download URL.
///
/// This file is generated by a build process and should not be edited manually.
/// It provides the specific version and base download URL used by [ChromeDriverManager].
library;
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated at: 2026-01-04T16:28:24.262290Z

/// The latest known good version of ChromeDriver based on fetch time.
const String chromeDriverVersion = '144.0.7559.31';

/// The base URL prefix for downloading ChromeDriver assets.
/// Specific version, platform, and filename should be appended.
/// Example structure: [chromeDriverBaseUrl]/[chromeDriverVersion]/[platform]/[filename]
const String chromeDriverBaseUrl =
    'https://storage.googleapis.com/chrome-for-testing-public';

/// Map of platform identifiers to their complete download URLs.
/// Use this to look up the appropriate download URL for a specific platform.
const Map<String, String> chromeDriverUrls = {
  'linux64':
      'https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/linux64/chromedriver-linux64.zip',
  'mac-arm64':
      'https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/mac-arm64/chromedriver-mac-arm64.zip',
  'mac-x64':
      'https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/mac-x64/chromedriver-mac-x64.zip',
  'win32':
      'https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/win32/chromedriver-win32.zip',
  'win64':
      'https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/win64/chromedriver-win64.zip',
};

/// Map of platform identifiers to their download filenames.
/// Use this to determine the correct extraction path for a specific platform.
const Map<String, String> chromeDriverFilenames = {
  'linux64': 'chromedriver-linux64.zip',
  'mac-arm64': 'chromedriver-mac-arm64.zip',
  'mac-x64': 'chromedriver-mac-x64.zip',
  'win32': 'chromedriver-win32.zip',
  'win64': 'chromedriver-win64.zip',
};

/// The detected platform at build time (for reference only).
/// At runtime, use platform detection logic to select the appropriate URL.
const String buildTimePlatform = 'linux64';
