import 'dart:math';

import 'package:server_contracts/server_contracts.dart';

/// Tracks version identifiers for a group of cache invalidation tags.
///
/// Resetting a tag changes its stored identifier. Tagged keys that include the
/// old identifier then become unreachable without scanning every cache value.
class TagSet {
  /// Constructs a [TagSet] with the given [store] and an optional list of
  /// [names].
  ///
  /// If [names] is not provided, it defaults to an empty list.
  TagSet(this.store, [this.names = const []]);

  /// The cache store where the tags are stored.
  final Store store;

  /// The tag names included in the namespace, in stable order.
  final List<String> names;

  /// Resets all tags in the [names] list.
  ///
  /// This method iterates over each tag name in the [names] list and calls
  /// [resetTag] on it.
  Future<void> reset() async {
    for (final name in names) {
      await resetTag(name);
    }
  }

  /// Resets a specific tag by [name].
  ///
  /// This method generates a unique ID for the tag and stores it in the cache
  /// store with a key generated by [tagKey]. The tag is stored indefinitely.
  ///
  /// Returns the generated unique ID for the tag.
  Future<String> resetTag(String name) async {
    final id = _generateUniqueId();
    await store.forever(tagKey(name), id);
    return id;
  }

  /// Flushes all tags in the [names] list.
  ///
  /// This method iterates over each tag name in the [names] list and calls
  /// [flushTag] on it.
  Future<void> flush() async {
    for (final name in names) {
      await flushTag(name);
    }
  }

  /// Flushes a specific tag by [name].
  ///
  /// This method removes the tag from the cache store using the key generated
  /// by [tagKey].
  Future<void> flushTag(String name) async {
    await store.forget(tagKey(name));
  }

  /// Returns the namespace formed by the current IDs for all [names].
  ///
  /// This method maps each tag name in the [names] list to its corresponding
  /// tag ID using [tagId], and then joins them with a `|` separator.
  ///
  /// Returns the namespace string.
  Future<String> getNamespace() async {
    final ids = await tagIds();
    return ids.join('|');
  }

  /// Resolves the current ID for each configured tag.
  ///
  /// This method maps each tag name in the [names] list to its corresponding
  /// tag ID using [tagId] and returns the list of tag IDs.
  ///
  /// Returns the list of tag IDs.
  Future<List<String>> tagIds() async {
    final ids = <String>[];
    for (final name in names) {
      ids.add(await tagId(name));
    }
    return ids;
  }

  /// Returns the current ID for [name], creating one when absent.
  ///
  /// This method gets the tag ID from the cache store using the key generated
  /// by [tagKey]. If the tag ID is not found, it calls [resetTag] to generate a
  /// new ID and store it.
  ///
  /// Returns the tag ID.
  Future<String> tagId(String name) async {
    final value = await store.get(tagKey(name));
    if (value != null) {
      return value.toString();
    }
    return resetTag(name);
  }

  /// Returns the backend key used to persist the version for [name].
  ///
  /// This method constructs the cache key by prefixing the tag name with
  /// `tag:` and suffixing it with `:key`.
  ///
  /// Returns the generated cache key.
  String tagKey(String name) {
    return 'tag:$name:key';
  }

  /// Retrieves the list of tag names.
  ///
  /// Returns the list of tag names.
  List<String> getNames() {
    return names;
  }

  /// A monotonically increasing in-process sequence used to disambiguate tag
  /// IDs that would otherwise be generated within the same millisecond,
  /// including across distinct [TagSet] instances sharing one store.
  static int _seq = 0;
  static final Random _random = Random();

  /// Generates a unique ID for a tag.
  ///
  /// Combines the current timestamp, a shared in-process counter, and a random
  /// suffix so IDs stay distinct across resets, instances, and processes.
  ///
  /// Returns the generated unique ID.
  String _generateUniqueId() {
    final id =
        '${DateTime.now().millisecondsSinceEpoch}-'
        '${_seq++}-${_random.nextInt(1 << 32)}';
    return id;
  }
}
