// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated at: 2025-10-13T16:48:22.739486

import 'browser_json.dart';

final browserJsonData = BrowserJson(
  comment: 'Do not edit this file, use utils/roll_browser.js',
  browsers: [
    BrowserEntry(
      name: 'chromium',
      revision: '1194',
      browserVersion: '141.0.7390.37',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-headless-shell',
      revision: '1194',
      browserVersion: '141.0.7390.37',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-tip-of-tree',
      revision: '1371',
      browserVersion: '142.0.7430.0',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-tip-of-tree-headless-shell',
      revision: '1371',
      browserVersion: '142.0.7430.0',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'firefox',
      revision: '1495',
      browserVersion: '142.0.1',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'firefox-beta',
      revision: '1490',
      browserVersion: '143.0b10',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'webkit',
      revision: '2215',
      browserVersion: '26.0',
      installByDefault: true,
      revisionOverrides: {
        'debian11-x64': '2105',
        'debian11-arm64': '2105',
        'mac10.14': '1446',
        'mac10.15': '1616',
        'mac11': '1816',
        'mac11-arm64': '1816',
        'mac12': '2009',
        'mac12-arm64': '2009',
        'mac13': '2140',
        'mac13-arm64': '2140',
        'ubuntu20.04-x64': '2092',
        'ubuntu20.04-arm64': '2092',
      },
    ),
    BrowserEntry(
      name: 'ffmpeg',
      revision: '1011',
      browserVersion: null,
      installByDefault: true,
      revisionOverrides: {'mac12': '1010', 'mac12-arm64': '1010'},
    ),
    BrowserEntry(
      name: 'winldd',
      revision: '1007',
      browserVersion: null,
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'android',
      revision: '1001',
      browserVersion: null,
      installByDefault: false,
      revisionOverrides: null,
    ),
  ],
);
