name: routed_architecture_database_app
description: Routed database provider architecture example.
publish_to: none
version: 0.1.0

resolution: workspace

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  ormed: ^0.4.0
  ormed_sqlite: ^0.4.1
  routed:
    path: ../../../packages/routed
  routed_database:
    path: ../../../packages/routed_database
  routed_io:
    path: ../../../packages/routed_io

dev_dependencies:
  lints: ^6.0.0
