version: 2
updates:
  - package-ecosystem: "pub"
    directories:
      - packages/**/*
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: "widen"
    open-pull-requests-limit: 1