# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml
analyzer:
  errors:
    depend_on_referenced_packages: ignore
    invalid_use_of_visible_for_testing_member: ignore
    strict_top_level_inference: ignore
    inference_failure_on_uninitialized_variable: ignore
    prefer_typing_uninitialized_variables: ignore
    avoid_renaming_method_parameters: ignore
    implementation_imports: ignore
    unused_import: ignore
    unused_local_variable: ignore
    unused_element: ignore
    sort_pub_dependencies: ignore
    undefined_shown_name: ignore
    invalid_annotation_target: ignore
    override_on_non_overriding_member: ignore
linter:
  rules:
    avoid_renaming_method_parameters: false
    implementation_imports: false
    prefer_typing_uninitialized_variables: false
    strict_top_level_inference: false
    inference_failure_on_uninitialized_variable: false
    unused_import: false
    unused_local_variable: false
    unused_element: false
    sort_pub_dependencies: false
    undefined_shown_name: false
  
  exclude: 
    - benchmarks/**
# Uncomment the following section to specify additional rules.

# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
