import 'package:property_testing/property_testing.dart';
import 'package:server_auth/server_auth.dart';
import 'package:test/test.dart';

Generator<List<int>> _bytes() =>
    Gen.integer(min: 0, max: 255).list(minLength: 1, maxLength: 64);

Generator<String> _hostileCodes() {
  return Gen.frequency<String>([
    (5, Chaos.string(minLength: 0, maxLength: 200)),
    (
      2,
      Gen.oneOf<String>([
        '000000',
        '１２３４５６',
        "' OR '1'='1",
        '<script>alert(1)</script>',
        'code\r\nSet-Cookie: attacker=1',
        '🔐-recovery-secret',
        'A' * 1000,
      ]),
    ),
  ]);
}

Generator<List<int>> _commandSequences() =>
    Gen.integer(min: 0, max: 4).list(minLength: 1, maxLength: 80);

String _propertyReport(PropertyResult result) {
  if (result.success) return 'All ${result.numTests} generated cases passed';
  return [
    'Property failed after ${result.numTests} cases',
    'Original input: ${result.originalFailingInput}',
    'Shrunk input: ${result.failingInput}',
    'Shrinks: ${result.numShrinks}',
    'Error: ${result.error}',
    'Seed: ${result.seed}',
  ].join('\n');
}

void _expectNoSensitiveKeys(Object? value) {
  if (value is Map) {
    for (final entry in value.entries) {
      final normalized = entry.key.toString().toLowerCase().replaceAll(
        RegExp('[^a-z0-9]'),
        '',
      );
      expect(
        normalized,
        isNot(anyOf('secret', 'recoverycodes', 'recoverycodehashes')),
        reason: 'Sensitive two-factor field survived status projection',
      );
      _expectNoSensitiveKeys(entry.value);
    }
  } else if (value is Iterable) {
    for (final item in value) {
      _expectNoSensitiveKeys(item);
    }
  }
}

List<int> Function(int length) _uniqueGenerator() {
  var sequence = 0;
  return (length) {
    final current = sequence++;
    return List<int>.generate(
      length,
      (index) => (current * 31 + index + 1) & 0xff,
    );
  };
}

void main() {
  test('base32 round trips arbitrary generated bytes', () async {
    final runner = PropertyTestRunner<List<int>>(_bytes(), (bytes) {
      final encoded = encodeAuthBase32(bytes);
      expect(decodeAuthBase32(encoded), equals(bytes));
    }, PropertyConfig(numTests: 500, seed: 20260819));

    final result = await runner.run();
    expect(result.success, isTrue, reason: _propertyReport(result));
  });

  test('hostile TOTP and recovery inputs stay inside auth errors', () async {
    final now = DateTime.utc(2030);
    final runner = PropertyTestRunner<String>(_hostileCodes(), (code) async {
      final feature = TwoFactorPlugin<Object>(
        backend: InMemoryAuthTwoFactorBackend(),
        secretProtector: const PlaintextAuthTwoFactorSecretProtector(),
        secretGenerator: _uniqueGenerator(),
      );
      final enrollment = await feature.beginEnrollment('user-1', now: now);
      final validCode = generateAuthTotpCode(
        enrollment.secret,
        timestampSeconds: now.millisecondsSinceEpoch ~/ 1000,
      );
      await feature.verifyEnrollment('user-1', validCode, now: now);

      if (code != validCode) {
        await expectLater(
          () => feature.verifyTotp('user-1', code, now: now),
          throwsA(
            isA<AuthFlowException>().having(
              (error) => error.code,
              'code',
              anyOf('two_factor_invalid_code', 'two_factor_locked'),
            ),
          ),
        );
      }
      await expectLater(
        () => feature.useRecoveryCode('user-1', code),
        throwsA(
          isA<AuthFlowException>().having(
            (error) => error.code,
            'code',
            equals('two_factor_invalid_recovery_code'),
          ),
        ),
      );

      _expectNoSensitiveKeys(
        (await feature.status('user-1', now: now)).toJson(),
      );
    }, PropertyConfig(numTests: 500, seed: 20260819));

    final result = await runner.run();
    expect(result.success, isTrue, reason: _propertyReport(result));
  });

  test('hostile persisted secrets never escape verification errors', () async {
    final now = DateTime.utc(2030);
    final runner = PropertyTestRunner<String>(_hostileCodes(), (secret) async {
      final store = InMemoryAuthTwoFactorStore();
      store.save(
        AuthTwoFactorRecord(
          userId: 'user-1',
          protectedSecret: secret.isEmpty ? '!' : secret,
          verified: true,
          enrollmentExpiresAt: now.add(const Duration(hours: 1)),
        ),
      );
      final feature = TwoFactorPlugin<Object>(
        backend: InMemoryAuthTwoFactorBackend(factorStore: store),
        secretProtector: const PlaintextAuthTwoFactorSecretProtector(),
      );

      await expectLater(
        () => feature.verifyTotp('user-1', 'not-a-code', now: now),
        throwsA(
          isA<AuthFlowException>().having(
            (error) => error.code,
            'code',
            anyOf('two_factor_invalid_code', 'two_factor_locked'),
          ),
        ),
      );
    }, PropertyConfig(numTests: 500, seed: 20260819));

    final result = await runner.run();
    expect(result.success, isTrue, reason: _propertyReport(result));
  });

  test(
    'stateful atomic command sequences preserve factor invariants',
    () async {
      final now = DateTime.utc(2030);
      final runner = PropertyTestRunner<List<int>>(_commandSequences(), (
        operations,
      ) async {
        final backend = InMemoryAuthTwoFactorBackend();
        const userId = 'stateful-user';
        backend.factorStore.save(
          AuthTwoFactorRecord(
            userId: userId,
            protectedSecret: 'protected-secret',
            enrollmentExpiresAt: now.add(const Duration(minutes: 10)),
            verified: true,
            recoveryCodeHashes: const <String>['initial-recovery'],
            updatedAt: now,
          ),
        );

        for (var index = 0; index < operations.length; index++) {
          final current = backend.factorStore.findByUserId(userId);
          final policy = AuthTwoFactorAttemptPolicy(
            now: now,
            maxAttempts: 5,
            lockoutDuration: const Duration(minutes: 5),
          );
          switch (operations[index]) {
            case 0:
              if (current != null) {
                await backend.verifyTotp(
                  AuthTwoFactorVerifyTotpCommand(
                    expected: current,
                    valid: true,
                    policy: policy,
                  ),
                );
              }
            case 1:
              await backend.useRecoveryCode(
                AuthTwoFactorUseRecoveryCodeCommand(
                  userId: userId,
                  recoveryCodeHash: 'initial-recovery',
                  policy: policy,
                ),
              );
            case 2:
              await backend.useRecoveryCode(
                AuthTwoFactorUseRecoveryCodeCommand(
                  userId: userId,
                  recoveryCodeHash: 'invalid-$index',
                  policy: policy,
                ),
              );
            case 3:
              if (current != null) {
                await backend.regenerateRecoveryCodes(
                  AuthTwoFactorRegenerateRecoveryCodesCommand(
                    expected: current,
                    valid: true,
                    recoveryCodeHashes: <String>['replacement-$index'],
                    policy: policy,
                  ),
                );
              }
            case 4:
              if (current != null) {
                await backend.disable(
                  AuthTwoFactorDisableCommand(
                    expected: current,
                    valid: true,
                    policy: policy,
                  ),
                );
              }
          }

          final after = backend.factorStore.findByUserId(userId);
          if (after != null) {
            expect(after.failedVerificationCount, inInclusiveRange(0, 5));
            expect(
              after.recoveryCodeHashes.toSet(),
              hasLength(after.recoveryCodeHashes.length),
            );
            expect(after.recoveryCodeHashes, isNot(contains('invalid-$index')));
          }
        }
      }, PropertyConfig(numTests: 200, seed: 20260820));

      final result = await runner.run();
      expect(result.success, isTrue, reason: _propertyReport(result));
    },
  );
}
