/// Generated constants related to the GeckoDriver version and download URL.
///
/// This file is generated by a build process (likely `build_runner`) and should
/// not be edited manually. It provides the specific version and base download
/// URL used by the [GeckoDriverManager].
library;
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated at: 2025-03-19T08:17:06.089378

/// The latest version of GeckoDriver
/// The hardcoded version string for the GeckoDriver to be used.
const geckoDriverVersion = 'v0.36.0';

/// The base URL for GeckoDriver downloads
/// The base URL for GeckoDriver release downloads on GitHub.
const geckoDriverBaseUrl =
    'https://github.com/mozilla/geckodriver/releases/download';
