name: server_testing
description: A starting point for Dart libraries or applications.
version: 0.0.1-alpha
repository: https://github.com/kingwill101/routed/tree/master/packages/server_testing

resolution: workspace
environment:
  sdk: '>=3.6.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  stack_trace: ^1.12.1
  html: ^0.15.5
  crypto: ^3.0.6
#  routed: 0.0.1
  meta: ^1.16.0
  http: ^1.3.0
  http_parser: ^4.1.2
  webdriver: ^3.1.0
  archive: ^4.0.5
  yaml: ^3.1.3
  mockito: ^5.4.5
  test: ^1.25.15
  build: ^2.4.2
  assertable_json: ^0.2.1
  
dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.4.15
  very_good_analysis: ^7.0.0
  build_config: ^1.1.2
