name: server_testing
description: Reusable server testing library for Dart.
version: 0.0.1-alpha
repository: https://github.com/kingwill101/routed/tree/master/packages/server_testing
tags:
  - server-testing
  - testing
  - server
  - testing-library

resolution: workspace
environment:
  sdk: '>=3.6.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  archive: ^4.0.5
  assertable_json: ^0.2.1
  build: ^2.4.2
  crypto: ^3.0.6
  html: ^0.15.5
  http: ^1.3.0
  http_parser: ^4.1.2
  meta: ^1.16.0
  mockito: ^5.4.5
  path: ^1.9.1
  stack_trace: ^1.12.1
#  routed: 0.0.1
  test: ^1.25.15
  webdriver: ^3.1.0
  yaml: ^3.1.3

dev_dependencies:
  build_config: ^1.1.2
  build_runner: ^2.4.15
  lints: ^5.1.1
  very_good_analysis: ^7.0.0
