
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;

Builder scaffoldTemplateEmbedBuilder(BuilderOptions options) =>
    _ScaffoldTemplateEmbedBuilder();

class _ScaffoldTemplateEmbedBuilder implements Builder {
  static const _outputPath = 'lib/src/console/create/templates_embedded.dart';
  static final _templateGlob = Glob('templates/scaffold/**');

  @override
  Map<String, List<String>> get buildExtensions => {
    r'$package$': [_outputPath],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final assets = <AssetId>[];
    await for (final asset in buildStep.findAssets(_templateGlob)) {
      assets.add(asset);
    }

    assets.sort((a, b) => a.path.compareTo(b.path));
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// Generated by scaffoldTemplateEmbedBuilder')
      ..writeln()
      ..writeln("import 'dart:typed_data';")
      ..writeln()
      ..writeln('final Map<String, Uint8List> scaffoldTemplateBytes = {');

    for (final asset in assets) {
      final bytes = await buildStep.readAsBytes(asset);
      final key = _relativeKey(asset.path);
      buffer.write("  '${_escape(key)}': Uint8List.fromList(<int>[");
      buffer.write(bytes.join(','));
      buffer.writeln(']),');
    }
    buffer.writeln('};');

    final output = AssetId(buildStep.inputId.package, _outputPath);
    await buildStep.writeAsString(output, buffer.toString());
  }

  String _relativeKey(String assetPath) {
    final rel = p.relative(assetPath, from: 'templates/scaffold');
    return p.posix.normalize(rel.replaceAll('\\', '/'));
  }

  String _escape(String value) {
    return value.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
  }
}
