import 'package:server_testing/src/browser/bootstrap/browser_manager.dart';
import 'package:server_testing/src/browser/bootstrap/progress.dart';
import 'package:server_testing/src/browser/bootstrap/proxy.dart';
import 'package:server_testing/src/browser/bootstrap/version.dart';

/// Generates a default set of WebDriver capabilities for the specified [browserName].
///
/// Includes common options like headless mode (if applicable) and attempts to
/// set the browser binary path using [BrowserManager.getBrowserPath].
Map<String, dynamic> _defaultCapabilities(String browserName) {
  final browserPath = BrowserManager.getBrowserPath(browserName);

  return {
    'browserName': browserName,
    if (browserName == 'chrome')
      'goog:chromeOptions': {
        'args': ['--headless', '--disable-gpu', '--no-sandbox'],
        if (browserPath != null) 'binary': browserPath,
      },
    if (browserName == 'firefox')
      'moz:firefoxOptions': {
        'args': ['-headless'],
        if (browserPath != null) 'binary': browserPath,
      },
  };
}

/// Defines configuration options for launching and running browser-based tests.
///
/// Configuration options for browser-based tests.
///
/// Controls browser type, WebDriver settings, timeouts, proxy configuration,
/// and other test environment options.
///
/// ```dart
/// final config = BrowserConfig(
///   browserName: 'firefox',
///   headless: false,
///   baseUrl: 'http://localhost:3000',
///   timeout: Duration(seconds: 60),
/// );
///
/// final browser = await launchBrowser(config);
/// ```
///
/// This class allows specifying various settings that control the test environment,
/// including:
/// *   The type and version of the browser to use.
/// *   WebDriver server connection details.
/// *   Default timeouts for operations.
/// *   Paths for logs and screenshots.
/// *   Whether to run in headless mode.
/// *   Proxy settings.
///
/// Instances of this class are typically passed to [testBootstrap], [browserTest],
/// [browserGroup], or [launchBrowser].
///
/// ### Example
///
/// ```dart
/// final config = BrowserConfig(
///   browserName: 'firefox', // Use Firefox instead of default Chrome
///   headless: false,        // Run with the browser window visible
///   baseUrl: 'http://localhost:3000', // Set the base URL for relative visits
///   timeout: Duration(seconds: 60),  // Increase default timeout
///   verbose: true,          // Enable verbose logging
/// );
///
/// // Use the config when setting up tests
/// await testBootstrap(config);
///
/// browserTest('User profile page', (browser) async {
///   // ... test implementation ...
/// }, config: config); // Optionally override global config for a specific test
/// ```
class BrowserConfig {
  /// The name of the browser to use (e.g., 'chrome', 'firefox').
  /// The name of the browser to use (e.g., 'chrome', 'firefox', 'webkit').
  /// Defaults to 'chrome'.
  final String browserName;
  
  /// The specific version of the browser to use.
  /// The specific [Version] of the browser to request. If `null`, the default
  /// version specified by the registry or manager will be used.
  final Version? version;
  
  /// Whether to automatically download the browser if not available.
  /// Whether to automatically download and install the browser if it's not
  /// found locally. Defaults to `true`.
  final bool autoDownload;
  
  /// The URL of the Selenium server.
  /// The URL of the WebDriver server (e.g., Selenium Grid or local ChromeDriver/GeckoDriver).
  /// Defaults to `http://localhost:4444/wd/hub`.
  final String seleniumUrl;
  
  /// WebDriver capabilities to pass to the browser.
  /// Custom WebDriver capabilities to merge with the defaults when launching
  /// the browser session. Defaults are generated by [_defaultCapabilities].
  final Map<String, dynamic> capabilities;
  
  /// The base URL for the application under test.
  /// The base URL for the application under test. Used by `browser.visit()`
  /// to resolve relative URLs. Defaults to `http://localhost:8000`.
  final String? baseUrl;
  
  /// The directory where screenshots will be saved.
  /// The directory where screenshots should be saved (e.g., on test failure).
  /// Defaults to `test/screenshots`.
  final String screenshotPath;
  
  /// The timeout duration for browser operations.
  /// The default timeout duration for browser operations (like finding elements,
  /// waiting for conditions). Defaults to 30 seconds.
  final Duration timeout;
  
  /// The proxy configuration for the browser.
  /// The optional [ProxyConfiguration] to use for browser connections.
  /// If `null`, no proxy is used.
  final ProxyConfiguration? proxy;
  
  /// Whether to enable browser cache between tests.
  /// Whether to attempt to enable browser caching between tests.
  ///
  /// Note: The actual effect depends on the WebDriver implementation and browser.
  /// Defaults to `true`.
  final bool enableCache;
  
  /// Callback function for browser download progress updates.
  /// An optional callback function invoked during browser downloads to report
  /// progress. Receives [BrowserDownloadProgress] updates.
  final BrowserDownloadProgress Function(BrowserDownloadProgress)?
      onDownloadProgress;
  
  /// Whether to run the browser in headless mode.
  /// Whether to run the browser in headless mode (without a visible UI window).
  /// Defaults to `true`.
  final bool headless;
  
  /// Whether to reinstall the browser even if already installed.
  /// Whether to force reinstallation of the browser binary, even if it appears
  /// to be already installed. Defaults to `false`.
  final bool forceReinstall;
  
  /// Whether to output verbose logs.
  /// Whether to enable verbose logging output during test setup and execution.
  /// Defaults to `false`.
  final bool verbose;
  
  /// The directory where logs will be saved.
  /// The directory where test logs should be saved. Defaults to `test/logs`.
  final String logDir;
  
  /// Whether to enable debug mode.
  /// Whether to enable debug mode, which might enable more detailed logging
  /// or change other behaviors. Defaults to `false`.
  final bool debug;

  /// Creates a new [BrowserConfig] instance.
  ///
  /// Creates a browser configuration with the specified options.
  ///
  /// Any unspecified options use reasonable defaults.
  ///
  /// Allows setting various configuration options. Unspecified options will use
  /// their default values (e.g., `browserName` defaults to 'chrome', `headless`
  /// defaults to `true`).
  ///
  /// The [capabilities] map allows providing specific WebDriver capabilities that
  /// will be merged with the default capabilities generated based on the
  /// [browserName] and other settings.
  BrowserConfig({
    this.browserName = 'chrome',
    this.version,
    this.debug = false,
    this.autoDownload = true,
    this.seleniumUrl = 'http://localhost:4444/wd/hub',
    Map<String, dynamic>? capabilities,
    this.baseUrl = 'http://localhost:8000',
    this.screenshotPath = 'test/screenshots',
    this.headless = true,
    this.timeout = const Duration(seconds: 30),
    this.proxy,
    this.enableCache = true,
    this.onDownloadProgress,
    this.logDir = 'test/logs',
    this.verbose = false,
    this.forceReinstall = false,
  }) : capabilities = capabilities ?? _defaultCapabilities(browserName);

  /// Creates a new [BrowserConfig] instance with values copied from this
  /// instance, overriding specific fields with the provided non-null values.
  /// Creates a copy of this configuration with the specified overrides.
  BrowserConfig copyWith({
    String? browserName,
    Version? version,
    bool? autoDownload,
    String? seleniumUrl,
    Map<String, dynamic>? capabilities,
    String? baseUrl,
    String? screenshotPath,
    bool? headless,
    Duration? timeout,
    ProxyConfiguration? proxy,
    bool? enableCache,
    BrowserDownloadProgress Function(BrowserDownloadProgress)?
        onDownloadProgress,
  }) {
    return BrowserConfig(
      browserName: browserName ?? this.browserName,
      version: version ?? this.version,
      autoDownload: autoDownload ?? this.autoDownload,
      seleniumUrl: seleniumUrl ?? this.seleniumUrl,
      capabilities: capabilities ?? this.capabilities,
      baseUrl: baseUrl ?? this.baseUrl,
      screenshotPath: screenshotPath ?? this.screenshotPath,
      headless: headless ?? this.headless,
      timeout: timeout ?? this.timeout,
      proxy: proxy ?? this.proxy,
      enableCache: enableCache ?? this.enableCache,
      onDownloadProgress: onDownloadProgress ?? this.onDownloadProgress,
    );
  }
}
