#pragma once

/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen on the Dart side.
*/

typedef signed int int32_t;
typedef unsigned short uint16_t;
typedef unsigned char uint8_t;


typedef struct ProxyServerHandle ProxyServerHandle;

typedef struct RoutedFfiProxyConfig {
  const char *host;
  uint16_t port;
  const char *backend_host;
  uint16_t backend_port;
  uint8_t backend_kind;
  const char *backend_path;
  uint8_t http3;
  const char *tls_cert_path;
  const char *tls_key_path;
  uint8_t benchmark_mode;
} RoutedFfiProxyConfig;

int32_t routed_ffi_transport_version(void);

struct ProxyServerHandle *routed_ffi_start_proxy_server(const struct RoutedFfiProxyConfig *config,
                                                        uint16_t *out_port);

void routed_ffi_stop_proxy_server(struct ProxyServerHandle *handle);
