#pragma once

/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen on the Dart side.
*/

typedef signed int int32_t;
typedef unsigned int uint32_t;
typedef unsigned short uint16_t;
typedef unsigned char uint8_t;
typedef unsigned long long uint64_t;


typedef struct ProxyServerHandle ProxyServerHandle;

typedef struct RoutedFfiProxyConfig {
  const char *host;
  uint16_t port;
  const char *backend_host;
  uint16_t backend_port;
  uint8_t backend_kind;
  const char *backend_path;
  uint32_t backlog;
  uint8_t v6_only;
  uint8_t shared;
  uint8_t request_client_certificate;
  uint8_t http3;
  const char *tls_cert_path;
  const char *tls_key_path;
  const char *tls_cert_password;
  uint8_t benchmark_mode;
  const void *direct_request_callback;
} RoutedFfiProxyConfig;

int32_t routed_ffi_transport_version(void);

struct ProxyServerHandle *routed_ffi_start_proxy_server(const struct RoutedFfiProxyConfig *config,
                                                        uint16_t *out_port);

void routed_ffi_stop_proxy_server(struct ProxyServerHandle *handle);

uint8_t routed_ffi_push_direct_response_frame(struct ProxyServerHandle *handle,
                                              uint64_t request_id,
                                              const uint8_t *response_payload,
                                              uint64_t response_payload_len);

uint8_t routed_ffi_complete_direct_request(struct ProxyServerHandle *handle,
                                           uint64_t request_id,
                                           const uint8_t *response_payload,
                                           uint64_t response_payload_len);
