import 'dart:async';

import 'package:build/build.dart';
import 'package:routed_openapi/routed_openapi.dart' as routed_openapi;

/// A build-runner builder that generates OpenAPI artifacts for Routed.
///
/// The builder delegates manifest conversion to `routed_openapi`. It reads the
/// route manifest generated by the CLI, then produces an OpenAPI 3.1 document
/// and a Dart controller in the consuming package.
///
/// Most applications register this builder through `build.yaml`, where
/// [openApiBuilder] is used as the build-runner factory. Constructing it
/// directly is useful when inspecting its [buildExtensions] or composing a
/// custom build configuration.
class OpenApiBuilder implements Builder {
  /// Creates a builder with optional OpenAPI generation options.
  ///
  /// [config] uses the same keys as the `build.yaml` options map. Supported
  /// keys include `title`, `version`, `description`, `manifest_path`,
  /// `serve_path`, `include_hidden`, and `servers`. If omitted, the builder
  /// uses the underlying generator's defaults.
  ///
  /// ```dart
  /// final builder = OpenApiBuilder(<String, dynamic>{
  ///   'title': 'Accounts API',
  ///   'version': '1.0.0',
  ///   'serve_path': '/openapi.json',
  /// });
  /// ```
  OpenApiBuilder([Map<String, dynamic>? config])
    : _delegate = routed_openapi.openApiBuilder(
        BuilderOptions(config ?? const <String, dynamic>{}),
      );

  final Builder _delegate;

  /// The generated OpenAPI document and serving controller paths.
  @override
  Map<String, List<String>> get buildExtensions => _delegate.buildExtensions;

  /// Generates the OpenAPI artifacts for [buildStep].
  ///
  /// The build step is expected to provide the route manifest configured for
  /// this builder. When the manifest is not available, the underlying builder
  /// logs a warning and returns without writing generated files.
  @override
  FutureOr<void> build(BuildStep buildStep) => _delegate.build(buildStep);
}

/// Creates the builder registered with build-runner.
///
/// [options] contains the builder options declared in `build.yaml`. The
/// returned builder writes `lib/generated/openapi.json` and
/// `lib/generated/openapi_controller.g.dart` for the consuming package.
Builder openApiBuilder(BuilderOptions options) =>
    OpenApiBuilder(options.config);
