// Mocks generated by Mockito 5.4.6 from annotations
// in class_view/test/shared/mock_adapter.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:class_view/src/adapter/view_adapter.dart' as _i2;
import 'package:class_view/src/view/form/fields/file.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ViewAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewAdapter extends _i1.Mock implements _i2.ViewAdapter {
  @override
  _i3.Future<String> getMethod() =>
      (super.noSuchMethod(
            Invocation.method(#getMethod, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getMethod, [])),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getMethod, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<Uri> getUri() =>
      (super.noSuchMethod(
            Invocation.method(#getUri, []),
            returnValue: _i3.Future<Uri>.value(
              _FakeUri_0(this, Invocation.method(#getUri, [])),
            ),
            returnValueForMissingStub: _i3.Future<Uri>.value(
              _FakeUri_0(this, Invocation.method(#getUri, [])),
            ),
          )
          as _i3.Future<Uri>);

  @override
  _i3.Future<String?> getParam(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getParam, [name]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<Map<String, String>> getParams() =>
      (super.noSuchMethod(
            Invocation.method(#getParams, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<Map<String, String>> getQueryParams() =>
      (super.noSuchMethod(
            Invocation.method(#getQueryParams, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<Map<String, String>> getRouteParams() =>
      (super.noSuchMethod(
            Invocation.method(#getRouteParams, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<Map<String, String>> getHeaders() =>
      (super.noSuchMethod(
            Invocation.method(#getHeaders, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<String?> getHeader(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getHeader, [name]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String> getBody() =>
      (super.noSuchMethod(
            Invocation.method(#getBody, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getBody, [])),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getBody, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> getJsonBody() =>
      (super.noSuchMethod(
            Invocation.method(#getJsonBody, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getFormData() =>
      (super.noSuchMethod(
            Invocation.method(#getFormData, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<_i5.FormFile?> getUploadedFile(String? fieldName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadedFile, [fieldName]),
            returnValue: _i3.Future<_i5.FormFile?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.FormFile?>.value(),
          )
          as _i3.Future<_i5.FormFile?>);

  @override
  _i3.Future<List<_i5.FormFile>> getUploadedFiles() =>
      (super.noSuchMethod(
            Invocation.method(#getUploadedFiles, []),
            returnValue: _i3.Future<List<_i5.FormFile>>.value(<_i5.FormFile>[]),
            returnValueForMissingStub: _i3.Future<List<_i5.FormFile>>.value(
              <_i5.FormFile>[],
            ),
          )
          as _i3.Future<List<_i5.FormFile>>);

  @override
  _i3.Future<bool> hasFile(String? fieldName) =>
      (super.noSuchMethod(
            Invocation.method(#hasFile, [fieldName]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setStatusCode(int? code) =>
      (super.noSuchMethod(
            Invocation.method(#setStatusCode, [code]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setHeader(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [name, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> write(String? body) =>
      (super.noSuchMethod(
            Invocation.method(#write, [body]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> writeJson(
    Map<String, dynamic>? data, {
    int? statusCode = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeJson, [data], {#statusCode: statusCode}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> redirect(String? url, {int? statusCode = 302}) =>
      (super.noSuchMethod(
            Invocation.method(#redirect, [url], {#statusCode: statusCode}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setup() =>
      (super.noSuchMethod(
            Invocation.method(#setup, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> teardown() =>
      (super.noSuchMethod(
            Invocation.method(#teardown, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
