targets:
  $default:
    builders:
      mockito|mockBuilder:
        generate_for:
          - lib/**.dart
      routed_testing|browser_json_builder:
        enabled: true
        generate_for:
          - lib/src/browser/bootstrap/browser_json.dart
builders:
  browser_json_builder:
    import: "package:routed_testing/src/builder/browser_json_builder.dart"
    builder_factories: [ "createBrowserJsonBuilder" ]
    build_extensions: { "lib/src/browser/bootstrap/browser_json.dart": [ "lib/src/browser/bootstrap/browsers_json_const.dart" ] }
    build_to: source
    auto_apply: dependents