name: routed_testing
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace
environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  mockito: ^5.4.5
  test: ^1.25.14
  routed: any
  meta: ^1.16.0
  http: ^1.3.0
  http_parser: ^4.1.2

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.4.14
  json_serializable: ^6.9.3