name: routed_testing
description: A starting point for Dart libraries or applications.
version: 0.0.1-alpha
repository: https://github.com/kingwill101/routed/tree/master/packages/routed_testing

resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  routed: 0.0.1
  meta: ^1.16.0
  test: ^1.25.15
  server_testing:

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.4.15
  very_good_analysis: ^7.0.0
  build_config: ^1.1.2
