name: routed_testing
description: A starting point for Dart libraries or applications.
version: 0.0.1-alpha
repository: https://github.com/kingwill101/routed/tree/master/packages/routed_testing

resolution: workspace
environment:
  sdk: '>=3.6.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  routed: 0.0.1-alpha
  server_testing: 0.0.1-alpha
  test: ^1.25.15

dev_dependencies:
  build_config: ^1.1.2
  build_runner: ^2.4.15
  lints: ^5.1.1
  very_good_analysis: ^7.0.0
