targets:
  $default:
    builders:
      routed|openapi:
        options:
          title: "OpenAPI Demo"
          version: "1.0.0"
          description: "A demonstration API showing OpenAPI 3.1 spec generation with routed."
          servers:
            - url: "http://localhost:8080"
              description: "Local development"
