name: server_testing_shelf
description: Adapter for the Shelf package to use server_testing for HTTP testing.
version: 0.1.0
repository: https://github.com/your-org/server_testing_shelf

resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  server_testing:
  meta: ^1.9.0
  shelf:

dev_dependencies:
  shelf_router:
  
