name: server_testing_shelf
description: Adapter for the Shelf package to use server_testing for HTTP testing.
version: 0.0.1-alpha
repository: https://github.com/kingwill101/routed/tree/master/packages/server_testing_shelf

resolution: workspace
environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  server_testing: 0.0.1-alpha
  meta: ^1.16.0
  shelf:

dev_dependencies:
  shelf_router:
