/// Provides the default `browsers.json` data embedded in the package.
///
/// This data is used by the [BrowserJsonLoader] when a `browsers.json` file
/// is not found in the project's root directory. It defines the standard set
/// of browsers and their revisions supported by the testing framework.
library;
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated at: 2025-03-19T08:15:32.499243

import 'browser_json.dart';

/// The default [BrowserJson] data used when `browsers.json` is not found.
final browserJsonData = BrowserJson(
  comment: 'Do not edit this file, use utils/roll_browser.js',
  browsers: [
    BrowserEntry(
      name: 'chromium',
      revision: '1163',
      browserVersion: '135.0.7049.17',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-headless-shell',
      revision: '1163',
      browserVersion: '135.0.7049.17',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-tip-of-tree',
      revision: '1312',
      browserVersion: '136.0.7066.0',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-tip-of-tree-headless-shell',
      revision: '1312',
      browserVersion: '136.0.7066.0',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'firefox',
      revision: '1477',
      browserVersion: '136.0',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'firefox-beta',
      revision: '1473',
      browserVersion: '137.0b2',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'webkit',
      revision: '2149',
      browserVersion: '18.4',
      installByDefault: true,
      revisionOverrides: {
        'debian11-x64': '2105',
        'debian11-arm64': '2105',
        'mac10.14': '1446',
        'mac10.15': '1616',
        'mac11': '1816',
        'mac11-arm64': '1816',
        'mac12': '2009',
        'mac12-arm64': '2009',
        'mac13': '2140',
        'mac13-arm64': '2140',
        'ubuntu20.04-x64': '2092',
        'ubuntu20.04-arm64': '2092'
      },
    ),
    BrowserEntry(
      name: 'ffmpeg',
      revision: '1011',
      browserVersion: null,
      installByDefault: true,
      revisionOverrides: {'mac12': '1010', 'mac12-arm64': '1010'},
    ),
    BrowserEntry(
      name: 'winldd',
      revision: '1007',
      browserVersion: null,
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'android',
      revision: '1001',
      browserVersion: null,
      installByDefault: false,
      revisionOverrides: null,
    )
  ],
);
