include: package:lints/recommended.yaml

analyzer:
  exclude:
    - templates/scaffold/**
  errors:
    depend_on_referenced_packages: ignore
    invalid_use_of_visible_for_testing_member: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - empty_catches
    - hash_and_equals
    - implementation_imports
    - non_constant_identifier_names
    - package_names
    - package_prefixed_library_names
    - prefer_const_constructors
    - prefer_is_empty
    - sort_pub_dependencies
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
