targets:
  $default:
    sources:
      - "$package$"
      - "lib/$lib$"
      - "lib/**"
      - "bin/**"
      - "test/**"
      - "example/**"
      - "tool/**"
      - "web/**"
      - "templates/**"
    builders:
      routed|scaffold_template_embed:
        generate_for:
          - "$package$"
      routed|openapi:
        generate_for:
          - "$package$"
        options:
          title: "API"
          version: "1.0.0"

builders:
  scaffold_template_embed:
    import: "package:routed/src/console/create/template_embed_builder.dart"
    builder_factories: ["scaffoldTemplateEmbedBuilder"]
    build_extensions: {"$package$": ["lib/src/console/create/templates_embedded.dart"]}
    auto_apply: root_package
    build_to: source
  openapi:
    import: "package:routed/src/openapi/openapi_builder.dart"
    builder_factories: ["openApiBuilder"]
    build_extensions: {"$package$": ["lib/generated/openapi.json", "lib/generated/openapi_controller.g.dart"]}
    auto_apply: none
    build_to: source
