name: todo_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
publish_to: none
environment:
  sdk: ">=3.9.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  class_view:
  test: ^1.24.0
  server_testing:

