library;
// Batteries-included bundle per refactor.md §12: re-exports the Routed
// framework core plus all official feature packages and routed_* adapters.
// Routed's own duplicate copies of portable runtime symbols (cache, auth,
// storage, session, gates, config helpers) are hidden so collisions resolve
// to the portable server_* / routed_* packages.
export 'package:server_auth/server_auth.dart';
export 'package:server_cache/server_cache.dart';
export 'package:server_sessions/server_sessions.dart';
export 'package:server_storage/server_storage.dart';
export 'package:server_rate_limit/server_rate_limit.dart';
export 'package:routed_auth/routed_auth.dart';
export 'package:routed_cache/routed_cache.dart';
export 'package:routed_sessions/routed_sessions.dart';
export 'package:routed_storage/routed_storage.dart';
export 'package:routed_rate_limit/routed_rate_limit.dart';

export 'package:routed/routed.dart' hide ArrayLock, ArrayStore, ArrayStoreFactory, AuthAccount, AuthAdapter, AuthCallbacks, AuthConfig, AuthConfigSpec, AuthCreateUserEvent, AuthCredentials, AuthEmailRequest, AuthEventConfig, AuthFlowException, AuthGuard, AuthJwtCallback, AuthJwtCallbackContext, AuthJwtConfig, AuthLinkAccountEvent, AuthManager, AuthOptions, AuthPrincipal, AuthProfileMapper, AuthProvider, AuthProviderRegistration, AuthProviderRegistry, AuthProviderType, AuthRedirectCallback, AuthRedirectCallbackContext, AuthResult, AuthRoutes, AuthServiceProvider, AuthSession, AuthSessionCallback, AuthSessionCallbackContext, AuthSessionConfig, AuthSessionEvent, AuthSessionStrategy, AuthSignInCallback, AuthSignInCallbackContext, AuthSignInEvent, AuthSignInResult, AuthSignOutEvent, AuthUpdateUserEvent, AuthUser, AuthVerificationToken, AuthVerificationTokenStore, CacheLock, CallbackAuthAdapter, CallbackProvider, CallbackResult, ConfigSchema, CredentialsAuthorize, CredentialsProvider, CredentialsRegister, EmailProvider, EmailSendCallback, FileLock, FileStore, FileStoreFactory, GateDefaults, GateDefinition, GateDeniedHandler, GatePayloadProvider, GateType, GateViolation, GuardDefinition, GuardResult, GuardType, Haigate, HaigateConfig, InMemoryAuthAdapter, InMemoryAuthVerificationTokenStore, InMemoryRememberTokenStore, JwtAuthException, JwtIssuer, JwtOptions, JwtPayload, JwtSessionOptions, JwtVerifier, NullLock, NullStore, NullStoreFactory, OAuth2Client, OAuth2Exception, OAuthIntrospectionConfig, OAuthIntrospectionOptions, OAuthIntrospectionResult, OAuthProfileCallback, OAuthProfileParser, OAuthProfileRequest, OAuthProfileSerializer, OAuthProvider, OAuthStateCallback, OAuthTokenResponse, OAuthUserInfoRequest, Policy, PolicyAction, PolicyBinding, PolicyOptions, ProviderConfigException, RbacAbility, RbacOptions, RememberTokenStore, RepositoryImpl, SessionAuth, SessionAuthService, SessionRememberMeConfig, StorageDisk, StorageManager, StoreFactory, TagSet, TaggableStore, TaggedCache, WebAuthnAuthenticationOptions, WebAuthnAuthenticator, WebAuthnAuthenticatorSelection, WebAuthnFormField, WebAuthnGetRelyingParty, WebAuthnGetUserInfo, WebAuthnProvider, WebAuthnRegistrationOptions, WebAuthnRelyingParty, WebAuthnUserInfo, guardMiddleware, jwtAuthentication, jwtClaimsAttribute, jwtHeadersAttribute, jwtSecretKey, jwtSubjectAttribute, oauth2Introspection, oauthClaimsAttribute, oauthScopeAttribute, oauthTokenAttribute, parseBoolLike, parseDurationLike, parseIntLike, parseMapList, parseStringLike, parseStringList, parseStringMap, parseStringMapAllowNulls, policyGate, rbacGate, registerPoliciesWithHaigate, registerPolicyBindings, registerPolicyBindingsSafely, registerRbacAbilities, registerRbacAbilitiesSafely, requireAuthenticated, requireRoles, stringKeyedMap;
