// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated at: 2025-02-07T11:27:45.245768

import 'browser_json.dart';

final browserJsonData = BrowserJson(
  comment: 'Do not edit this file, use utils/roll_browser.js',
  browsers: [
    BrowserEntry(
      name: 'chromium',
      revision: '1157',
      browserVersion: '133.0.6943.35',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-headless-shell',
      revision: '1157',
      browserVersion: '133.0.6943.35',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-tip-of-tree',
      revision: '1300',
      browserVersion: '134.0.6998.0',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'chromium-tip-of-tree-headless-shell',
      revision: '1300',
      browserVersion: '134.0.6998.0',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'firefox',
      revision: '1474',
      browserVersion: '134.0',
      installByDefault: true,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'firefox-beta',
      revision: '1470',
      browserVersion: '135.0b10',
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'webkit',
      revision: '2130',
      browserVersion: '18.2',
      installByDefault: true,
      revisionOverrides: {
        'debian11-x64': '2105',
        'debian11-arm64': '2105',
        'mac10.14': '1446',
        'mac10.15': '1616',
        'mac11': '1816',
        'mac11-arm64': '1816',
        'mac12': '2009',
        'mac12-arm64': '2009',
        'ubuntu20.04-x64': '2092',
        'ubuntu20.04-arm64': '2092'
      },
    ),
    BrowserEntry(
      name: 'ffmpeg',
      revision: '1011',
      browserVersion: null,
      installByDefault: true,
      revisionOverrides: {'mac12': '1010', 'mac12-arm64': '1010'},
    ),
    BrowserEntry(
      name: 'winldd',
      revision: '1007',
      browserVersion: null,
      installByDefault: false,
      revisionOverrides: null,
    ),
    BrowserEntry(
      name: 'android',
      revision: '1001',
      browserVersion: null,
      installByDefault: false,
      revisionOverrides: null,
    )
  ],
);
