// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int32 Function()>()
external int routed_ffi_transport_version();

@ffi.Native<
  ffi.Pointer<ProxyServerHandle> Function(
    ffi.Pointer<RoutedFfiProxyConfig>,
    ffi.Pointer<ffi.Uint16>,
  )
>()
external ffi.Pointer<ProxyServerHandle> routed_ffi_start_proxy_server(
  ffi.Pointer<RoutedFfiProxyConfig> config,
  ffi.Pointer<ffi.Uint16> out_port,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ProxyServerHandle>)>()
external void routed_ffi_stop_proxy_server(
  ffi.Pointer<ProxyServerHandle> handle,
);

final class ProxyServerHandle extends ffi.Opaque {}

final class RoutedFfiProxyConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> host;

  @ffi.Uint16()
  external int port;

  external ffi.Pointer<ffi.Char> backend_host;

  @ffi.Uint16()
  external int backend_port;

  @ffi.Uint8()
  external int backend_kind;

  external ffi.Pointer<ffi.Char> backend_path;

  @ffi.Uint8()
  external int http3;

  external ffi.Pointer<ffi.Char> tls_cert_path;

  external ffi.Pointer<ffi.Char> tls_key_path;

  @ffi.Uint8()
  external int benchmark_mode;
}
